-- AlterTable
ALTER TABLE `user` ADD COLUMN `reputationPoints` INTEGER NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE `ReputationAction` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `actionType` ENUM('REGISTER_EMAIL', 'REGISTER_IRL', 'REGISTER_POSTAL', 'HAS_REGISTERED_IRL', 'SEND_INVITE', 'ANSWER_QUESTION', 'ARGUMENT_ANSWER', 'CREATE_ANSWER', 'UPVOTE_ARGUMENT', 'FLAG_ARGUMENT', 'EDIT_ARGUMENT') NOT NULL,
    `createdOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ReputationAction` ADD CONSTRAINT `ReputationAction_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
